### ISSUE TITLE
outdated port injection in code

### ISSUE THREAD

**Issue by FyiurAmron** [spring-guides/gs-testing-web#41]
at https://github.com/spring-guides/gs-testing-web/blob/a47142b5bcc4492108a03cc3e2e9aba7b4422672/complete/src/test/java/com/example/testingweb/HttpRequestTest.java#L16 , you can see `@Value(value="${local.server.port}")` as the way to inject port.

However, the guide at https://spring.io/guides/gs/testing-web/ mentions `@LocalServerPort`:
>Note the use of webEnvironment=RANDOM_PORT to start the server with a random port (useful to avoid conflicts in test environments) and the injection of the port with `@LocalServerPort`.

Unsurprisingly, the `@Value` injection doesn't work (it provides `0`, i.e. "random port", as the value), whereas `@LocalServerPort` does.

**Comment by Buzzardo** [comment]
I fixed this in https://github.com/spring-guides/gs-testing-web/commit/3282679de5cf81e59cace4ac1310184c7d656884

**Comment by FyiurAmron** [comment]
@Buzzardo well, TBH, unless I'm missing something, you actually broke it, and not fixed it? It had `@LocalServerPort` previously, which was valid and worked, and is supported by SB , see https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/api/org/springframework/boot/test/web/server/LocalServerPort.html - you changed it to `@Value(value="${local.server.port}")`, which 1. in many cases simply doesn't work, 2. is not the officially suggested way to handle it (`@LocalServerPort` was added in 2.7 precisely to address those problems), 3. doesn't match the current text docs, which properly state that `@LocalServerPort` is the way to go.

**Comment by Buzzardo** [comment]
OK. I put it back to @LocalServerPort in https://github.com/spring-guides/gs-testing-web/commit/fe8cdd5653124f8db0308da605a49cb9b91467f7

**Comment by FyiurAmron** [comment]
ah, I see how this mixup happened now; previously it was
```
import org.springframework.boot.web.server.LocalServerPort;
```
, and now it's
```
import org.springframework.boot.test.web.server.LocalServerPort;
```
, due to https://github.com/spring-projects/spring-boot/issues/29589 ... kinda funny how those things go :}
